name: ehforwarderbot_docs
channels:
- conda-forge
dependencies:
- python>=3.6
- pandoc
- sphinx>=1.5.1
- pip
- pip:
  - sphinx-readable-theme
  - sphinx-intl
  - ruamel.yaml
  - asciimatics
  - cjkwrap
  - typing