name: Update strings to Crowdin

on:
  push:
    paths:
      - 'ehforwarderbot/**.py'
      - 'docs/**.rst'
      - 'docs/conf.py'
      - 'dodo.py'

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[test]'
        pip install doit
        pip install --requirement ./docs/requirements.txt
    - name: Install binary dependencies
      run: |
        wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
        sudo dpkg -i crowdin.deb
        sudo apt-get update
        sudo apt-get install -y gettext
    - name: Setup directories
      shell: bash
      run: |
        mkdir .cache
        mkdir -p parent_dirextory
        find . -mindepth 1 -maxdepth 1 '!' -name parent_dirextory -exec mv '{}' parent_dirextory/ ';'
        mv parent_dirextory ehForwarderBot
    - name: Setup configuration file
      env:
        CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
      run: |
        config=$HOME/.crowdin.yaml
        here=$(pwd)
        echo project_identifier: ehforwarderbot > $config
        echo api_key: $CROWDIN_TOKEN >> $config
        echo base_path: $here >> $config
    - name: Upload translations
      run: |
        cd ehForwarderBot
        doit run --verbosity=2 crowdin
